/*
 * This file is generated by jOOQ.
 */
package me.fagiolini.cinemapp.db;


import java.util.Arrays;
import java.util.List;

import me.fagiolini.cinemapp.db.tables.Cinema;
import me.fagiolini.cinemapp.db.tables.Film;
import me.fagiolini.cinemapp.db.tables.Prenotazione;
import me.fagiolini.cinemapp.db.tables.Proiezione;
import me.fagiolini.cinemapp.db.tables.Sala;
import me.fagiolini.cinemapp.db.tables.Utente;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Cinemapp extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cinemapp</code>
     */
    public static final Cinemapp CINEMAPP = new Cinemapp();

    /**
     * The table <code>cinemapp.cinema</code>.
     */
    public final Cinema CINEMA = Cinema.CINEMA;

    /**
     * The table <code>cinemapp.film</code>.
     */
    public final Film FILM = Film.FILM;

    /**
     * The table <code>cinemapp.prenotazione</code>.
     */
    public final Prenotazione PRENOTAZIONE = Prenotazione.PRENOTAZIONE;

    /**
     * The table <code>cinemapp.proiezione</code>.
     */
    public final Proiezione PROIEZIONE = Proiezione.PROIEZIONE;

    /**
     * The table <code>cinemapp.sala</code>.
     */
    public final Sala SALA = Sala.SALA;

    /**
     * The table <code>cinemapp.utente</code>.
     */
    public final Utente UTENTE = Utente.UTENTE;

    /**
     * No further instances allowed
     */
    private Cinemapp() {
        super("cinemapp", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Cinema.CINEMA,
            Film.FILM,
            Prenotazione.PRENOTAZIONE,
            Proiezione.PROIEZIONE,
            Sala.SALA,
            Utente.UTENTE
        );
    }
}
