/*
 * This file is generated by jOOQ.
 */
package me.fagiolini.cinemapp.db;


import me.fagiolini.cinemapp.db.tables.Cinema;
import me.fagiolini.cinemapp.db.tables.Film;
import me.fagiolini.cinemapp.db.tables.Prenotazione;
import me.fagiolini.cinemapp.db.tables.Proiezione;
import me.fagiolini.cinemapp.db.tables.Sala;
import me.fagiolini.cinemapp.db.tables.Utente;


/**
 * Convenience access to all tables in cinemapp.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>cinemapp.cinema</code>.
     */
    public static final Cinema CINEMA = Cinema.CINEMA;

    /**
     * The table <code>cinemapp.film</code>.
     */
    public static final Film FILM = Film.FILM;

    /**
     * The table <code>cinemapp.prenotazione</code>.
     */
    public static final Prenotazione PRENOTAZIONE = Prenotazione.PRENOTAZIONE;

    /**
     * The table <code>cinemapp.proiezione</code>.
     */
    public static final Proiezione PROIEZIONE = Proiezione.PROIEZIONE;

    /**
     * The table <code>cinemapp.sala</code>.
     */
    public static final Sala SALA = Sala.SALA;

    /**
     * The table <code>cinemapp.utente</code>.
     */
    public static final Utente UTENTE = Utente.UTENTE;
}
