/*
 * This file is generated by jOOQ.
 */
package me.fagiolini.cinemapp.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Film implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Integer durata;
    private String copertina;
    private String descrizione;
    private String genere;
    private String regia;
    private String titolo;

    public Film() {}

    public Film(Film value) {
        this.id = value.id;
        this.durata = value.durata;
        this.copertina = value.copertina;
        this.descrizione = value.descrizione;
        this.genere = value.genere;
        this.regia = value.regia;
        this.titolo = value.titolo;
    }

    public Film(
        Long id,
        Integer durata,
        String copertina,
        String descrizione,
        String genere,
        String regia,
        String titolo
    ) {
        this.id = id;
        this.durata = durata;
        this.copertina = copertina;
        this.descrizione = descrizione;
        this.genere = genere;
        this.regia = regia;
        this.titolo = titolo;
    }

    /**
     * Getter for <code>cinemapp.film.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>cinemapp.film.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>cinemapp.film.durata</code>.
     */
    public Integer getDurata() {
        return this.durata;
    }

    /**
     * Setter for <code>cinemapp.film.durata</code>.
     */
    public void setDurata(Integer durata) {
        this.durata = durata;
    }

    /**
     * Getter for <code>cinemapp.film.copertina</code>.
     */
    public String getCopertina() {
        return this.copertina;
    }

    /**
     * Setter for <code>cinemapp.film.copertina</code>.
     */
    public void setCopertina(String copertina) {
        this.copertina = copertina;
    }

    /**
     * Getter for <code>cinemapp.film.descrizione</code>.
     */
    public String getDescrizione() {
        return this.descrizione;
    }

    /**
     * Setter for <code>cinemapp.film.descrizione</code>.
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * Getter for <code>cinemapp.film.genere</code>.
     */
    public String getGenere() {
        return this.genere;
    }

    /**
     * Setter for <code>cinemapp.film.genere</code>.
     */
    public void setGenere(String genere) {
        this.genere = genere;
    }

    /**
     * Getter for <code>cinemapp.film.regia</code>.
     */
    public String getRegia() {
        return this.regia;
    }

    /**
     * Setter for <code>cinemapp.film.regia</code>.
     */
    public void setRegia(String regia) {
        this.regia = regia;
    }

    /**
     * Getter for <code>cinemapp.film.titolo</code>.
     */
    public String getTitolo() {
        return this.titolo;
    }

    /**
     * Setter for <code>cinemapp.film.titolo</code>.
     */
    public void setTitolo(String titolo) {
        this.titolo = titolo;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Film other = (Film) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.durata == null) {
            if (other.durata != null)
                return false;
        }
        else if (!this.durata.equals(other.durata))
            return false;
        if (this.copertina == null) {
            if (other.copertina != null)
                return false;
        }
        else if (!this.copertina.equals(other.copertina))
            return false;
        if (this.descrizione == null) {
            if (other.descrizione != null)
                return false;
        }
        else if (!this.descrizione.equals(other.descrizione))
            return false;
        if (this.genere == null) {
            if (other.genere != null)
                return false;
        }
        else if (!this.genere.equals(other.genere))
            return false;
        if (this.regia == null) {
            if (other.regia != null)
                return false;
        }
        else if (!this.regia.equals(other.regia))
            return false;
        if (this.titolo == null) {
            if (other.titolo != null)
                return false;
        }
        else if (!this.titolo.equals(other.titolo))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.durata == null) ? 0 : this.durata.hashCode());
        result = prime * result + ((this.copertina == null) ? 0 : this.copertina.hashCode());
        result = prime * result + ((this.descrizione == null) ? 0 : this.descrizione.hashCode());
        result = prime * result + ((this.genere == null) ? 0 : this.genere.hashCode());
        result = prime * result + ((this.regia == null) ? 0 : this.regia.hashCode());
        result = prime * result + ((this.titolo == null) ? 0 : this.titolo.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Film (");

        sb.append(id);
        sb.append(", ").append(durata);
        sb.append(", ").append(copertina);
        sb.append(", ").append(descrizione);
        sb.append(", ").append(genere);
        sb.append(", ").append(regia);
        sb.append(", ").append(titolo);

        sb.append(")");
        return sb.toString();
    }
}
