/*
 * This file is generated by jOOQ.
 */
package me.fagiolini.cinemapp.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Prenotazione implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Integer numeroBiglietti;
    private LocalDate dataPrenotazione;
    private Long proiezioneId;
    private Long utenteId;

    public Prenotazione() {}

    public Prenotazione(Prenotazione value) {
        this.id = value.id;
        this.numeroBiglietti = value.numeroBiglietti;
        this.dataPrenotazione = value.dataPrenotazione;
        this.proiezioneId = value.proiezioneId;
        this.utenteId = value.utenteId;
    }

    public Prenotazione(
        Long id,
        Integer numeroBiglietti,
        LocalDate dataPrenotazione,
        Long proiezioneId,
        Long utenteId
    ) {
        this.id = id;
        this.numeroBiglietti = numeroBiglietti;
        this.dataPrenotazione = dataPrenotazione;
        this.proiezioneId = proiezioneId;
        this.utenteId = utenteId;
    }

    /**
     * Getter for <code>cinemapp.prenotazione.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>cinemapp.prenotazione.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>cinemapp.prenotazione.numero_biglietti</code>.
     */
    public Integer getNumeroBiglietti() {
        return this.numeroBiglietti;
    }

    /**
     * Setter for <code>cinemapp.prenotazione.numero_biglietti</code>.
     */
    public void setNumeroBiglietti(Integer numeroBiglietti) {
        this.numeroBiglietti = numeroBiglietti;
    }

    /**
     * Getter for <code>cinemapp.prenotazione.data_prenotazione</code>.
     */
    public LocalDate getDataPrenotazione() {
        return this.dataPrenotazione;
    }

    /**
     * Setter for <code>cinemapp.prenotazione.data_prenotazione</code>.
     */
    public void setDataPrenotazione(LocalDate dataPrenotazione) {
        this.dataPrenotazione = dataPrenotazione;
    }

    /**
     * Getter for <code>cinemapp.prenotazione.proiezione_id</code>.
     */
    public Long getProiezioneId() {
        return this.proiezioneId;
    }

    /**
     * Setter for <code>cinemapp.prenotazione.proiezione_id</code>.
     */
    public void setProiezioneId(Long proiezioneId) {
        this.proiezioneId = proiezioneId;
    }

    /**
     * Getter for <code>cinemapp.prenotazione.utente_id</code>.
     */
    public Long getUtenteId() {
        return this.utenteId;
    }

    /**
     * Setter for <code>cinemapp.prenotazione.utente_id</code>.
     */
    public void setUtenteId(Long utenteId) {
        this.utenteId = utenteId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Prenotazione other = (Prenotazione) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.numeroBiglietti == null) {
            if (other.numeroBiglietti != null)
                return false;
        }
        else if (!this.numeroBiglietti.equals(other.numeroBiglietti))
            return false;
        if (this.dataPrenotazione == null) {
            if (other.dataPrenotazione != null)
                return false;
        }
        else if (!this.dataPrenotazione.equals(other.dataPrenotazione))
            return false;
        if (this.proiezioneId == null) {
            if (other.proiezioneId != null)
                return false;
        }
        else if (!this.proiezioneId.equals(other.proiezioneId))
            return false;
        if (this.utenteId == null) {
            if (other.utenteId != null)
                return false;
        }
        else if (!this.utenteId.equals(other.utenteId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.numeroBiglietti == null) ? 0 : this.numeroBiglietti.hashCode());
        result = prime * result + ((this.dataPrenotazione == null) ? 0 : this.dataPrenotazione.hashCode());
        result = prime * result + ((this.proiezioneId == null) ? 0 : this.proiezioneId.hashCode());
        result = prime * result + ((this.utenteId == null) ? 0 : this.utenteId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Prenotazione (");

        sb.append(id);
        sb.append(", ").append(numeroBiglietti);
        sb.append(", ").append(dataPrenotazione);
        sb.append(", ").append(proiezioneId);
        sb.append(", ").append(utenteId);

        sb.append(")");
        return sb.toString();
    }
}
