/*
 * This file is generated by jOOQ.
 */
package me.fagiolini.cinemapp.db.tables.pojos;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "sala",
    schema = "cinemapp"
)
public class Sala implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long cinemaId;
    private Integer capacita;
    private String numero;

    public Sala() {}

    public Sala(Sala value) {
        this.id = value.id;
        this.cinemaId = value.cinemaId;
        this.capacita = value.capacita;
        this.numero = value.numero;
    }

    public Sala(
        Long id,
        Long cinemaId,
        Integer capacita,
        String numero
    ) {
        this.id = id;
        this.cinemaId = cinemaId;
        this.capacita = capacita;
        this.numero = numero;
    }

    /**
     * Getter for <code>cinemapp.sala.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>cinemapp.sala.id</code>.
     */
    public Sala setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>cinemapp.sala.cinema_id</code>.
     */
    @Column(name = "cinema_id")
    public Long getCinemaId() {
        return this.cinemaId;
    }

    /**
     * Setter for <code>cinemapp.sala.cinema_id</code>.
     */
    public Sala setCinemaId(Long cinemaId) {
        this.cinemaId = cinemaId;
        return this;
    }

    /**
     * Getter for <code>cinemapp.sala.capacita</code>.
     */
    @Column(name = "capacita", nullable = false)
    @NotNull
    public Integer getCapacita() {
        return this.capacita;
    }

    /**
     * Setter for <code>cinemapp.sala.capacita</code>.
     */
    public Sala setCapacita(Integer capacita) {
        this.capacita = capacita;
        return this;
    }

    /**
     * Getter for <code>cinemapp.sala.numero</code>.
     */
    @Column(name = "numero", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    public String getNumero() {
        return this.numero;
    }

    /**
     * Setter for <code>cinemapp.sala.numero</code>.
     */
    public Sala setNumero(String numero) {
        this.numero = numero;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Sala other = (Sala) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.cinemaId == null) {
            if (other.cinemaId != null)
                return false;
        }
        else if (!this.cinemaId.equals(other.cinemaId))
            return false;
        if (this.capacita == null) {
            if (other.capacita != null)
                return false;
        }
        else if (!this.capacita.equals(other.capacita))
            return false;
        if (this.numero == null) {
            if (other.numero != null)
                return false;
        }
        else if (!this.numero.equals(other.numero))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.cinemaId == null) ? 0 : this.cinemaId.hashCode());
        result = prime * result + ((this.capacita == null) ? 0 : this.capacita.hashCode());
        result = prime * result + ((this.numero == null) ? 0 : this.numero.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Sala (");

        sb.append(id);
        sb.append(", ").append(cinemaId);
        sb.append(", ").append(capacita);
        sb.append(", ").append(numero);

        sb.append(")");
        return sb.toString();
    }
}
