/*
 * This file is generated by jOOQ.
 */
package me.fagiolini.cinemapp.db.tables.daos;


import java.util.List;
import java.util.Optional;

import me.fagiolini.cinemapp.db.tables.Film;
import me.fagiolini.cinemapp.db.tables.records.FilmRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FilmDao extends DAOImpl<FilmRecord, me.fagiolini.cinemapp.db.tables.pojos.Film, Long> {

    /**
     * Create a new FilmDao without any configuration
     */
    public FilmDao() {
        super(Film.FILM, me.fagiolini.cinemapp.db.tables.pojos.Film.class);
    }

    /**
     * Create a new FilmDao with an attached configuration
     */
    public FilmDao(Configuration configuration) {
        super(Film.FILM, me.fagiolini.cinemapp.db.tables.pojos.Film.class, configuration);
    }

    @Override
    public Long getId(me.fagiolini.cinemapp.db.tables.pojos.Film object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Film> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Film.FILM.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Film> fetchById(Long... values) {
        return fetch(Film.FILM.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public me.fagiolini.cinemapp.db.tables.pojos.Film fetchOneById(Long value) {
        return fetchOne(Film.FILM.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<me.fagiolini.cinemapp.db.tables.pojos.Film> fetchOptionalById(Long value) {
        return fetchOptional(Film.FILM.ID, value);
    }

    /**
     * Fetch records that have <code>durata BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Film> fetchRangeOfDurata(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Film.FILM.DURATA, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>durata IN (values)</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Film> fetchByDurata(Integer... values) {
        return fetch(Film.FILM.DURATA, values);
    }

    /**
     * Fetch records that have <code>copertina BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Film> fetchRangeOfCopertina(String lowerInclusive, String upperInclusive) {
        return fetchRange(Film.FILM.COPERTINA, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>copertina IN (values)</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Film> fetchByCopertina(String... values) {
        return fetch(Film.FILM.COPERTINA, values);
    }

    /**
     * Fetch records that have <code>descrizione BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Film> fetchRangeOfDescrizione(String lowerInclusive, String upperInclusive) {
        return fetchRange(Film.FILM.DESCRIZIONE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>descrizione IN (values)</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Film> fetchByDescrizione(String... values) {
        return fetch(Film.FILM.DESCRIZIONE, values);
    }

    /**
     * Fetch records that have <code>genere BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Film> fetchRangeOfGenere(String lowerInclusive, String upperInclusive) {
        return fetchRange(Film.FILM.GENERE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>genere IN (values)</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Film> fetchByGenere(String... values) {
        return fetch(Film.FILM.GENERE, values);
    }

    /**
     * Fetch records that have <code>regia BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Film> fetchRangeOfRegia(String lowerInclusive, String upperInclusive) {
        return fetchRange(Film.FILM.REGIA, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>regia IN (values)</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Film> fetchByRegia(String... values) {
        return fetch(Film.FILM.REGIA, values);
    }

    /**
     * Fetch records that have <code>titolo BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Film> fetchRangeOfTitolo(String lowerInclusive, String upperInclusive) {
        return fetchRange(Film.FILM.TITOLO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>titolo IN (values)</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Film> fetchByTitolo(String... values) {
        return fetch(Film.FILM.TITOLO, values);
    }
}
