/*
 * This file is generated by jOOQ.
 */
package me.fagiolini.cinemapp.db.tables.daos;


import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

import me.fagiolini.cinemapp.db.tables.Prenotazione;
import me.fagiolini.cinemapp.db.tables.records.PrenotazioneRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PrenotazioneDao extends DAOImpl<PrenotazioneRecord, me.fagiolini.cinemapp.db.tables.pojos.Prenotazione, Long> {

    /**
     * Create a new PrenotazioneDao without any configuration
     */
    public PrenotazioneDao() {
        super(Prenotazione.PRENOTAZIONE, me.fagiolini.cinemapp.db.tables.pojos.Prenotazione.class);
    }

    /**
     * Create a new PrenotazioneDao with an attached configuration
     */
    public PrenotazioneDao(Configuration configuration) {
        super(Prenotazione.PRENOTAZIONE, me.fagiolini.cinemapp.db.tables.pojos.Prenotazione.class, configuration);
    }

    @Override
    public Long getId(me.fagiolini.cinemapp.db.tables.pojos.Prenotazione object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Prenotazione> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Prenotazione.PRENOTAZIONE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Prenotazione> fetchById(Long... values) {
        return fetch(Prenotazione.PRENOTAZIONE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public me.fagiolini.cinemapp.db.tables.pojos.Prenotazione fetchOneById(Long value) {
        return fetchOne(Prenotazione.PRENOTAZIONE.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<me.fagiolini.cinemapp.db.tables.pojos.Prenotazione> fetchOptionalById(Long value) {
        return fetchOptional(Prenotazione.PRENOTAZIONE.ID, value);
    }

    /**
     * Fetch records that have <code>numero_biglietti BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Prenotazione> fetchRangeOfNumeroBiglietti(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Prenotazione.PRENOTAZIONE.NUMERO_BIGLIETTI, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>numero_biglietti IN (values)</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Prenotazione> fetchByNumeroBiglietti(Integer... values) {
        return fetch(Prenotazione.PRENOTAZIONE.NUMERO_BIGLIETTI, values);
    }

    /**
     * Fetch records that have <code>data_prenotazione BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Prenotazione> fetchRangeOfDataPrenotazione(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(Prenotazione.PRENOTAZIONE.DATA_PRENOTAZIONE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>data_prenotazione IN (values)</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Prenotazione> fetchByDataPrenotazione(LocalDate... values) {
        return fetch(Prenotazione.PRENOTAZIONE.DATA_PRENOTAZIONE, values);
    }

    /**
     * Fetch records that have <code>proiezione_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Prenotazione> fetchRangeOfProiezioneId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Prenotazione.PRENOTAZIONE.PROIEZIONE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>proiezione_id IN (values)</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Prenotazione> fetchByProiezioneId(Long... values) {
        return fetch(Prenotazione.PRENOTAZIONE.PROIEZIONE_ID, values);
    }

    /**
     * Fetch records that have <code>utente_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Prenotazione> fetchRangeOfUtenteId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Prenotazione.PRENOTAZIONE.UTENTE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>utente_id IN (values)</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Prenotazione> fetchByUtenteId(Long... values) {
        return fetch(Prenotazione.PRENOTAZIONE.UTENTE_ID, values);
    }
}
