/*
 * This file is generated by jOOQ.
 */
package me.fagiolini.cinemapp.db.tables.daos;


import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import me.fagiolini.cinemapp.db.tables.Proiezione;
import me.fagiolini.cinemapp.db.tables.records.ProiezioneRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProiezioneDao extends DAOImpl<ProiezioneRecord, me.fagiolini.cinemapp.db.tables.pojos.Proiezione, Long> {

    /**
     * Create a new ProiezioneDao without any configuration
     */
    public ProiezioneDao() {
        super(Proiezione.PROIEZIONE, me.fagiolini.cinemapp.db.tables.pojos.Proiezione.class);
    }

    /**
     * Create a new ProiezioneDao with an attached configuration
     */
    public ProiezioneDao(Configuration configuration) {
        super(Proiezione.PROIEZIONE, me.fagiolini.cinemapp.db.tables.pojos.Proiezione.class, configuration);
    }

    @Override
    public Long getId(me.fagiolini.cinemapp.db.tables.pojos.Proiezione object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Proiezione> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Proiezione.PROIEZIONE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Proiezione> fetchById(Long... values) {
        return fetch(Proiezione.PROIEZIONE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public me.fagiolini.cinemapp.db.tables.pojos.Proiezione fetchOneById(Long value) {
        return fetchOne(Proiezione.PROIEZIONE.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<me.fagiolini.cinemapp.db.tables.pojos.Proiezione> fetchOptionalById(Long value) {
        return fetchOptional(Proiezione.PROIEZIONE.ID, value);
    }

    /**
     * Fetch records that have <code>data_ora_fine BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Proiezione> fetchRangeOfDataOraFine(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Proiezione.PROIEZIONE.DATA_ORA_FINE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>data_ora_fine IN (values)</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Proiezione> fetchByDataOraFine(LocalDateTime... values) {
        return fetch(Proiezione.PROIEZIONE.DATA_ORA_FINE, values);
    }

    /**
     * Fetch records that have <code>data_ora_inizio BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Proiezione> fetchRangeOfDataOraInizio(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Proiezione.PROIEZIONE.DATA_ORA_INIZIO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>data_ora_inizio IN (values)</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Proiezione> fetchByDataOraInizio(LocalDateTime... values) {
        return fetch(Proiezione.PROIEZIONE.DATA_ORA_INIZIO, values);
    }

    /**
     * Fetch records that have <code>prezzo BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Proiezione> fetchRangeOfPrezzo(Double lowerInclusive, Double upperInclusive) {
        return fetchRange(Proiezione.PROIEZIONE.PREZZO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>prezzo IN (values)</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Proiezione> fetchByPrezzo(Double... values) {
        return fetch(Proiezione.PROIEZIONE.PREZZO, values);
    }

    /**
     * Fetch records that have <code>film_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Proiezione> fetchRangeOfFilmId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Proiezione.PROIEZIONE.FILM_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>film_id IN (values)</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Proiezione> fetchByFilmId(Long... values) {
        return fetch(Proiezione.PROIEZIONE.FILM_ID, values);
    }

    /**
     * Fetch records that have <code>sala_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Proiezione> fetchRangeOfSalaId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Proiezione.PROIEZIONE.SALA_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sala_id IN (values)</code>
     */
    public List<me.fagiolini.cinemapp.db.tables.pojos.Proiezione> fetchBySalaId(Long... values) {
        return fetch(Proiezione.PROIEZIONE.SALA_ID, values);
    }
}
