/*
 * This file is generated by jOOQ.
 */
package me.fagiolini.cinemapp.db.tables.records;


import me.fagiolini.cinemapp.db.tables.Cinema;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CinemaRecord extends UpdatableRecordImpl<CinemaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cinemapp.cinema.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cinemapp.cinema.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cinemapp.cinema.indirizzo</code>.
     */
    public void setIndirizzo(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cinemapp.cinema.indirizzo</code>.
     */
    public String getIndirizzo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cinemapp.cinema.nome</code>.
     */
    public void setNome(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cinemapp.cinema.nome</code>.
     */
    public String getNome() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cinemapp.cinema.telefono</code>.
     */
    public void setTelefono(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cinemapp.cinema.telefono</code>.
     */
    public String getTelefono() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CinemaRecord
     */
    public CinemaRecord() {
        super(Cinema.CINEMA);
    }

    /**
     * Create a detached, initialised CinemaRecord
     */
    public CinemaRecord(Long id, String indirizzo, String nome, String telefono) {
        super(Cinema.CINEMA);

        setId(id);
        setIndirizzo(indirizzo);
        setNome(nome);
        setTelefono(telefono);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CinemaRecord
     */
    public CinemaRecord(me.fagiolini.cinemapp.db.tables.pojos.Cinema value) {
        super(Cinema.CINEMA);

        if (value != null) {
            setId(value.getId());
            setIndirizzo(value.getIndirizzo());
            setNome(value.getNome());
            setTelefono(value.getTelefono());
            resetChangedOnNotNull();
        }
    }
}
