/*
 * This file is generated by jOOQ.
 */
package me.fagiolini.cinemapp.db.tables.records;


import me.fagiolini.cinemapp.db.tables.Film;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FilmRecord extends UpdatableRecordImpl<FilmRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cinemapp.film.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cinemapp.film.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cinemapp.film.durata</code>.
     */
    public void setDurata(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>cinemapp.film.durata</code>.
     */
    public Integer getDurata() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>cinemapp.film.copertina</code>.
     */
    public void setCopertina(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cinemapp.film.copertina</code>.
     */
    public String getCopertina() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cinemapp.film.descrizione</code>.
     */
    public void setDescrizione(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cinemapp.film.descrizione</code>.
     */
    public String getDescrizione() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cinemapp.film.genere</code>.
     */
    public void setGenere(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cinemapp.film.genere</code>.
     */
    public String getGenere() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cinemapp.film.regia</code>.
     */
    public void setRegia(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cinemapp.film.regia</code>.
     */
    public String getRegia() {
        return (String) get(5);
    }

    /**
     * Setter for <code>cinemapp.film.titolo</code>.
     */
    public void setTitolo(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>cinemapp.film.titolo</code>.
     */
    public String getTitolo() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FilmRecord
     */
    public FilmRecord() {
        super(Film.FILM);
    }

    /**
     * Create a detached, initialised FilmRecord
     */
    public FilmRecord(Long id, Integer durata, String copertina, String descrizione, String genere, String regia, String titolo) {
        super(Film.FILM);

        setId(id);
        setDurata(durata);
        setCopertina(copertina);
        setDescrizione(descrizione);
        setGenere(genere);
        setRegia(regia);
        setTitolo(titolo);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised FilmRecord
     */
    public FilmRecord(me.fagiolini.cinemapp.db.tables.pojos.Film value) {
        super(Film.FILM);

        if (value != null) {
            setId(value.getId());
            setDurata(value.getDurata());
            setCopertina(value.getCopertina());
            setDescrizione(value.getDescrizione());
            setGenere(value.getGenere());
            setRegia(value.getRegia());
            setTitolo(value.getTitolo());
            resetChangedOnNotNull();
        }
    }
}
