/*
 * This file is generated by jOOQ.
 */
package me.fagiolini.cinemapp.db.tables.records;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import me.fagiolini.cinemapp.db.tables.Film;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "film",
    schema = "cinemapp",
    uniqueConstraints = {
        @UniqueConstraint(name = "film_titolo_regia_key", columnNames = { "titolo", "regia" })
    }
)
public class FilmRecord extends UpdatableRecordImpl<FilmRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cinemapp.film.id</code>.
     */
    public FilmRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>cinemapp.film.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cinemapp.film.durata</code>.
     */
    public FilmRecord setDurata(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>cinemapp.film.durata</code>.
     */
    @Column(name = "durata", nullable = false)
    @NotNull
    public Integer getDurata() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>cinemapp.film.copertina</code>.
     */
    public FilmRecord setCopertina(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>cinemapp.film.copertina</code>.
     */
    @Column(name = "copertina", length = 255)
    @Size(max = 255)
    public String getCopertina() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cinemapp.film.descrizione</code>.
     */
    public FilmRecord setDescrizione(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>cinemapp.film.descrizione</code>.
     */
    @Column(name = "descrizione", length = 255)
    @Size(max = 255)
    public String getDescrizione() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cinemapp.film.genere</code>.
     */
    public FilmRecord setGenere(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>cinemapp.film.genere</code>.
     */
    @Column(name = "genere", length = 255)
    @Size(max = 255)
    public String getGenere() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cinemapp.film.regia</code>.
     */
    public FilmRecord setRegia(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>cinemapp.film.regia</code>.
     */
    @Column(name = "regia", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    public String getRegia() {
        return (String) get(5);
    }

    /**
     * Setter for <code>cinemapp.film.titolo</code>.
     */
    public FilmRecord setTitolo(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>cinemapp.film.titolo</code>.
     */
    @Column(name = "titolo", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    public String getTitolo() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FilmRecord
     */
    public FilmRecord() {
        super(Film.FILM);
    }

    /**
     * Create a detached, initialised FilmRecord
     */
    public FilmRecord(Long id, Integer durata, String copertina, String descrizione, String genere, String regia, String titolo) {
        super(Film.FILM);

        setId(id);
        setDurata(durata);
        setCopertina(copertina);
        setDescrizione(descrizione);
        setGenere(genere);
        setRegia(regia);
        setTitolo(titolo);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised FilmRecord
     */
    public FilmRecord(me.fagiolini.cinemapp.db.tables.pojos.Film value) {
        super(Film.FILM);

        if (value != null) {
            setId(value.getId());
            setDurata(value.getDurata());
            setCopertina(value.getCopertina());
            setDescrizione(value.getDescrizione());
            setGenere(value.getGenere());
            setRegia(value.getRegia());
            setTitolo(value.getTitolo());
            resetChangedOnNotNull();
        }
    }
}
