/*
 * This file is generated by jOOQ.
 */
package me.fagiolini.cinemapp.db.tables.records;


import java.time.LocalDate;

import me.fagiolini.cinemapp.db.tables.Prenotazione;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PrenotazioneRecord extends UpdatableRecordImpl<PrenotazioneRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cinemapp.prenotazione.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cinemapp.prenotazione.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cinemapp.prenotazione.numero_biglietti</code>.
     */
    public void setNumeroBiglietti(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>cinemapp.prenotazione.numero_biglietti</code>.
     */
    public Integer getNumeroBiglietti() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>cinemapp.prenotazione.data_prenotazione</code>.
     */
    public void setDataPrenotazione(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>cinemapp.prenotazione.data_prenotazione</code>.
     */
    public LocalDate getDataPrenotazione() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>cinemapp.prenotazione.proiezione_id</code>.
     */
    public void setProiezioneId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>cinemapp.prenotazione.proiezione_id</code>.
     */
    public Long getProiezioneId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>cinemapp.prenotazione.utente_id</code>.
     */
    public void setUtenteId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>cinemapp.prenotazione.utente_id</code>.
     */
    public Long getUtenteId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PrenotazioneRecord
     */
    public PrenotazioneRecord() {
        super(Prenotazione.PRENOTAZIONE);
    }

    /**
     * Create a detached, initialised PrenotazioneRecord
     */
    public PrenotazioneRecord(Long id, Integer numeroBiglietti, LocalDate dataPrenotazione, Long proiezioneId, Long utenteId) {
        super(Prenotazione.PRENOTAZIONE);

        setId(id);
        setNumeroBiglietti(numeroBiglietti);
        setDataPrenotazione(dataPrenotazione);
        setProiezioneId(proiezioneId);
        setUtenteId(utenteId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PrenotazioneRecord
     */
    public PrenotazioneRecord(me.fagiolini.cinemapp.db.tables.pojos.Prenotazione value) {
        super(Prenotazione.PRENOTAZIONE);

        if (value != null) {
            setId(value.getId());
            setNumeroBiglietti(value.getNumeroBiglietti());
            setDataPrenotazione(value.getDataPrenotazione());
            setProiezioneId(value.getProiezioneId());
            setUtenteId(value.getUtenteId());
            resetChangedOnNotNull();
        }
    }
}
