/*
 * This file is generated by jOOQ.
 */
package me.fagiolini.cinemapp.db.tables.records;


import java.time.LocalDateTime;

import me.fagiolini.cinemapp.db.tables.Proiezione;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProiezioneRecord extends UpdatableRecordImpl<ProiezioneRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cinemapp.proiezione.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cinemapp.proiezione.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cinemapp.proiezione.data_ora_fine</code>.
     */
    public void setDataOraFine(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>cinemapp.proiezione.data_ora_fine</code>.
     */
    public LocalDateTime getDataOraFine() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>cinemapp.proiezione.data_ora_inizio</code>.
     */
    public void setDataOraInizio(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>cinemapp.proiezione.data_ora_inizio</code>.
     */
    public LocalDateTime getDataOraInizio() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>cinemapp.proiezione.prezzo</code>.
     */
    public void setPrezzo(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>cinemapp.proiezione.prezzo</code>.
     */
    public Double getPrezzo() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>cinemapp.proiezione.film_id</code>.
     */
    public void setFilmId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>cinemapp.proiezione.film_id</code>.
     */
    public Long getFilmId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>cinemapp.proiezione.sala_id</code>.
     */
    public void setSalaId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>cinemapp.proiezione.sala_id</code>.
     */
    public Long getSalaId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProiezioneRecord
     */
    public ProiezioneRecord() {
        super(Proiezione.PROIEZIONE);
    }

    /**
     * Create a detached, initialised ProiezioneRecord
     */
    public ProiezioneRecord(Long id, LocalDateTime dataOraFine, LocalDateTime dataOraInizio, Double prezzo, Long filmId, Long salaId) {
        super(Proiezione.PROIEZIONE);

        setId(id);
        setDataOraFine(dataOraFine);
        setDataOraInizio(dataOraInizio);
        setPrezzo(prezzo);
        setFilmId(filmId);
        setSalaId(salaId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ProiezioneRecord
     */
    public ProiezioneRecord(me.fagiolini.cinemapp.db.tables.pojos.Proiezione value) {
        super(Proiezione.PROIEZIONE);

        if (value != null) {
            setId(value.getId());
            setDataOraFine(value.getDataOraFine());
            setDataOraInizio(value.getDataOraInizio());
            setPrezzo(value.getPrezzo());
            setFilmId(value.getFilmId());
            setSalaId(value.getSalaId());
            resetChangedOnNotNull();
        }
    }
}
