/*
 * This file is generated by jOOQ.
 */
package me.fagiolini.cinemapp.db.tables.records;


import me.fagiolini.cinemapp.db.tables.Sala;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SalaRecord extends UpdatableRecordImpl<SalaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cinemapp.sala.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cinemapp.sala.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cinemapp.sala.cinema_id</code>.
     */
    public void setCinemaId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>cinemapp.sala.cinema_id</code>.
     */
    public Long getCinemaId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>cinemapp.sala.capacita</code>.
     */
    public void setCapacita(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>cinemapp.sala.capacita</code>.
     */
    public Integer getCapacita() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>cinemapp.sala.numero</code>.
     */
    public void setNumero(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cinemapp.sala.numero</code>.
     */
    public String getNumero() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SalaRecord
     */
    public SalaRecord() {
        super(Sala.SALA);
    }

    /**
     * Create a detached, initialised SalaRecord
     */
    public SalaRecord(Long id, Long cinemaId, Integer capacita, String numero) {
        super(Sala.SALA);

        setId(id);
        setCinemaId(cinemaId);
        setCapacita(capacita);
        setNumero(numero);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SalaRecord
     */
    public SalaRecord(me.fagiolini.cinemapp.db.tables.pojos.Sala value) {
        super(Sala.SALA);

        if (value != null) {
            setId(value.getId());
            setCinemaId(value.getCinemaId());
            setCapacita(value.getCapacita());
            setNumero(value.getNumero());
            resetChangedOnNotNull();
        }
    }
}
