/*
 * This file is generated by jOOQ.
 */
package me.fagiolini.cinemapp.db.tables.records;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import me.fagiolini.cinemapp.db.tables.Sala;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "sala",
    schema = "cinemapp"
)
public class SalaRecord extends UpdatableRecordImpl<SalaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cinemapp.sala.id</code>.
     */
    public SalaRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>cinemapp.sala.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cinemapp.sala.cinema_id</code>.
     */
    public SalaRecord setCinemaId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>cinemapp.sala.cinema_id</code>.
     */
    @Column(name = "cinema_id")
    public Long getCinemaId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>cinemapp.sala.capacita</code>.
     */
    public SalaRecord setCapacita(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>cinemapp.sala.capacita</code>.
     */
    @Column(name = "capacita", nullable = false)
    @NotNull
    public Integer getCapacita() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>cinemapp.sala.numero</code>.
     */
    public SalaRecord setNumero(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>cinemapp.sala.numero</code>.
     */
    @Column(name = "numero", nullable = false, length = 255)
    @NotNull
    @Size(max = 255)
    public String getNumero() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SalaRecord
     */
    public SalaRecord() {
        super(Sala.SALA);
    }

    /**
     * Create a detached, initialised SalaRecord
     */
    public SalaRecord(Long id, Long cinemaId, Integer capacita, String numero) {
        super(Sala.SALA);

        setId(id);
        setCinemaId(cinemaId);
        setCapacita(capacita);
        setNumero(numero);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SalaRecord
     */
    public SalaRecord(me.fagiolini.cinemapp.db.tables.pojos.Sala value) {
        super(Sala.SALA);

        if (value != null) {
            setId(value.getId());
            setCinemaId(value.getCinemaId());
            setCapacita(value.getCapacita());
            setNumero(value.getNumero());
            resetChangedOnNotNull();
        }
    }
}
