/*
 * This file is generated by jOOQ.
 */
package me.fagiolini.cinemapp.db.tables.records;


import me.fagiolini.cinemapp.db.tables.Utente;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UtenteRecord extends UpdatableRecordImpl<UtenteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cinemapp.utente.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>cinemapp.utente.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>cinemapp.utente.ruolo</code>.
     */
    public void setRuolo(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>cinemapp.utente.ruolo</code>.
     */
    public Short getRuolo() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>cinemapp.utente.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cinemapp.utente.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cinemapp.utente.nome</code>.
     */
    public void setNome(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cinemapp.utente.nome</code>.
     */
    public String getNome() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cinemapp.utente.password</code>.
     */
    public void setPassword(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cinemapp.utente.password</code>.
     */
    public String getPassword() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UtenteRecord
     */
    public UtenteRecord() {
        super(Utente.UTENTE);
    }

    /**
     * Create a detached, initialised UtenteRecord
     */
    public UtenteRecord(Long id, Short ruolo, String email, String nome, String password) {
        super(Utente.UTENTE);

        setId(id);
        setRuolo(ruolo);
        setEmail(email);
        setNome(nome);
        setPassword(password);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UtenteRecord
     */
    public UtenteRecord(me.fagiolini.cinemapp.db.tables.pojos.Utente value) {
        super(Utente.UTENTE);

        if (value != null) {
            setId(value.getId());
            setRuolo(value.getRuolo());
            setEmail(value.getEmail());
            setNome(value.getNome());
            setPassword(value.getPassword());
            resetChangedOnNotNull();
        }
    }
}
